### ISSUE TITLE
How add toggle by CapsLock?

### ISSUE THREAD

**Issue by Belanchuk** [deficient/keyboard-layout-indicator#2]
Please, add example for toggle by CapsLock. )

**Comment by coldfix** [comment]
Hey,

First, I assume you want to disable the usual caps lock functionality. In order to do this, you can put the following command into autostart (e.g. into `.xinitrc`):

```
setxkbmap -option caps:none
```

you can also execute it manually during an X session. This command can also be used to remap the caps key to another function. For example, I have remapped it to _Escape_ (which I use a lot in vim) using `setxkbmap -option caps:escape` instead.

Now, you can add a keybinding to your `lua.rc`:

``` lua
local globalkeys = awful.util.table.join(
    ...
    awful.key({                    }, "VoidSymbol", function() kbdcfg:next() end ),
    ...
)
```

Note that the keymapping of course depends on how you redefined the key with the _setxkbmap_ command - `VoidSymbol` is the one belonging to `caps:none`. In general, if you want to see the name of a key you can start the `xev` program and then type the key you are interested in.

**Comment by Belanchuk** [comment]
Cool! This is work! )
